AWSTemplateFormatVersion: '2010-09-09'
Description: IAM policy and role for GitHub Actions and Lambda deployment

Resources:
  SQSWorkerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Full permissions for deploying SQS worker stack
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
              - ec2:*
              - s3:*
              - iam:*
              - autoscaling:*
              - cloudwatch:*
              - sqs:*
              - lambda:*
              - apigateway:*
            Resource: "*"

  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-ci-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Federated: arn:aws:iam::319319364622:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: "repo:dc-moses/sqs-autoscaling-worker:*"
      ManagedPolicyArns:
        - !Ref SQSWorkerPolicy