AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Worker Stack with Lambda-based ASG auto-scaling

Parameters:
  WorkerScriptBucket:
    Type: String
  WorkerScriptKey:
    Type: String
  SubnetId:
    Type: AWS::EC2::Subnet::Id

Resources:
  WorkerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: worker-queue

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId:
          Fn::Sub: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
        InstanceType: t2.micro
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo "[UserData] Bootstrapping instance..." >> /var/log/worker.log
            yum install -y python3 aws-cli >> /var/log/worker.log 2>&1

            echo "[UserData] Installing boto3..." >> /var/log/worker.log
            pip3 install boto3 >> /var/log/worker.log 2>&1

            echo "[UserData] Downloading worker script..." >> /var/log/worker.log
            aws s3 cp s3://${WorkerScriptBucket}/${WorkerScriptKey} /home/ec2-user/worker.py >> /var/log/worker.log 2>&1
            chmod +x /home/ec2-user/worker.py

            QUEUE_URL=$(aws cloudformation describe-stacks \
              --stack-name ${AWS::StackName} \
              --query "Stacks[0].Outputs[?OutputKey=='SQSQueueURL'].OutputValue" \
              --output text)

            echo "[UserData] Starting worker.py with QUEUE_URL=$QUEUE_URL" >> /var/log/worker.log
            nohup python3 /home/ec2-user/worker.py "$QUEUE_URL" >> /var/log/worker.log 2>&1 &

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 0
      MaxSize: 1
      DesiredCapacity: 0
      VPCZoneIdentifier:
        - !Ref SubnetId

  ASGScalerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ASGScalerRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ASGScalingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:SetDesiredCapacity
                  - autoscaling:DescribeAutoScalingGroups
                  - sqs:GetQueueAttributes
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ASGScalerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ASGScalerFunction
      Handler: lambda_trigger.lambda_handler
      Role: !GetAtt ASGScalerFunctionRole.Arn
      Runtime: python3.10
      Timeout: 30
      MemorySize: 128
      Code:
        ZipFile: |
          import boto3
          import os
          import time
          import botocore.exceptions

          def lambda_handler(event, context):
              sqs = boto3.client("sqs")
              asg = boto3.client("autoscaling")

              queue_url = os.environ.get("QUEUE_URL")
              asg_name = os.environ.get("ASG_NAME")

              if not queue_url or not asg_name:
                  print("[ERROR] Missing required environment variables.")
                  return {"statusCode": 500, "body": "Missing QUEUE_URL or ASG_NAME"}

              print(f"[ENV] QUEUE_URL={queue_url}")
              print(f"[ENV] ASG_NAME={asg_name}")

              try:
                  attrs = sqs.get_queue_attributes(
                      QueueUrl=queue_url,
                      AttributeNames=["ApproximateNumberOfMessages", "ApproximateNumberOfMessagesNotVisible"]
                  )
              except botocore.exceptions.ClientError as e:
                  print(f"[ERROR] Failed to fetch SQS attributes: {e}")
                  return {"statusCode": 500, "body": str(e)}

              visible = int(attrs["Attributes"].get("ApproximateNumberOfMessages", 0))
              not_visible = int(attrs["Attributes"].get("ApproximateNumberOfMessagesNotVisible", 0))
              total = visible + not_visible

              print(f"[SQS] Visible: {visible}, NotVisible: {not_visible}, Total: {total}")

              try:
                  group = asg.describe_auto_scaling_groups(AutoScalingGroupNames=[asg_name])["AutoScalingGroups"][0]
              except Exception as e:
                  print(f"[ERROR] Failed to fetch ASG info: {e}")
                  return {"statusCode": 500, "body": str(e)}

              current_capacity = group["DesiredCapacity"]
              print(f"[ASG] Current desired capacity: {current_capacity}")

              if total > 0 and current_capacity == 0:
                  print(f"[ASG] Scaling UP {asg_name} to 1")
                  asg.set_desired_capacity(AutoScalingGroupName=asg_name, DesiredCapacity=1, HonorCooldown=False)
              elif total == 0 and current_capacity > 0:
                  print(f"[ASG] Attempting to scale DOWN {asg_name} to 0")
                  for attempt in range(3):
                      try:
                          asg.set_desired_capacity(AutoScalingGroupName=asg_name, DesiredCapacity=0, HonorCooldown=False)
                          print(f"[ASG] Scale-down request successful on attempt {attempt + 1}")
                          break
                      except botocore.exceptions.ClientError as e:
                          print(f"[ASG] Attempt {attempt + 1} failed to scale down: {e}")
                          if attempt < 2:
                              time.sleep(5)
                          else:
                              print("[ASG] All scale-down attempts failed.")

              return {
                  "statusCode": 200,
                  "body": f"Queue={total}, DesiredCapacity={current_capacity}"
              }
      Environment:
        Variables:
          QUEUE_URL: !Ref WorkerQueue
          ASG_NAME: !Ref AutoScalingGroup

  ASGScalerSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: ASGScalerSchedule
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ASGScalerFunction.Arn
          Id: ASGScalerTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ASGScalerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ASGScalerSchedule.Arn

Outputs:
  SQSQueueURL:
    Value: !Ref WorkerQueue
    Export:
      Name: !Sub "${AWS::StackName}-QueueURL"

  LaunchTemplateId:
    Value: !Ref LaunchTemplate
    Export:
      Name: !Sub "${AWS::StackName}-LaunchTemplateId"

  AutoScalingGroupName:
    Value: !Ref AutoScalingGroup
    Export:
      Name: !Sub "${AWS::StackName}-ASGName"